name: PR에 Feature 브랜치 주소 코멘트 추가

on:
  workflow_call:
    inputs:
      bucket_name:
        required: true
        type: string
      pr_number:
        required: true
        type: number

jobs:
  s3_address:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: comment PR
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: "🍐 배포 주소: http://${{ inputs.bucket_name }}.s3-website.ap-northeast-2.amazonaws.com"
          pr-number: ${{ inputs.pr_number}}
